/*
 * Melon Disease Edge Classifier — main inference loop on EK-RA8P1.
 *
 * Hardware  : Renesas RA8P1 (Cortex-M85 @ 1GHz + Ethos-U55 @ 500MHz, 256MAC)
 * Toolchain : e² studio + FSP (Google TFLM Core + CMSIS-NN + ARM Ethos-U driver)
 * Output    : SEGGER RTT (J-Link on-board, no extra wiring)
 *
 * Flow per inference:
 *   1) preprocess uint8 HWC → float NCHW + ImageNet normalize
 *   2) memcpy into model input buffer
 *   3) reset PMU counters
 *   4) RunModel(false)   — calls CPU→NPU→CPU subgraphs
 *   5) read CPU cycles + NPU active/idle/axi counters
 *   6) argmax + softmax → print top-1 class with confidence + cycles
 */

#include "hal_data.h"
#include "SEGGER_RTT/SEGGER_RTT.h"
#include "pmu_ethosu.h"
#include "../../../ra/board/ra8p1_ek/board.h"

#include <stdio.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>

/* Generated by RUHMI from the trained ONNX model. */
#include "model.h"

/* Our test images + class names + labels (auto-generated by img_to_header.py). */
#include "test_imgs.h"
#include "preprocess.h"

/* Optional OSPI flash init — required because RUHMI placed weights in
 * .sdram_from_ospi0_cs1 (external SIP NOR flash). Provided by FSP / project
 * OSPI sample code; define one of these macros in your project build settings.
 */
#if RUN_MODEL_FROM_OSPI || RUN_MODEL_FROM_DOPI
#include "ospi_b_ep.h"
fsp_err_t ospi_b_init(void);
fsp_err_t ospi_b_set_protocol_to_opi(void);
#endif

void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0
        R_FACI_LP->DFLCTL = 1U;
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        R_IOPORT_Open(&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED
        R_BSP_SdramInit(true);
#endif

#if RUN_MODEL_FROM_OSPI || RUN_MODEL_FROM_DOPI
        if (ospi_b_init() != FSP_SUCCESS) return;
#if RUN_MODEL_FROM_DOPI
        ospi_b_set_protocol_to_opi();
#endif
#endif
    }
}

/* M85 PMU cycle counter (RUHMI sample uses the same API). */
static uint32_t pmu_get_cycles(void)
{
    static bool initialized = false;
    if (!initialized) {
        ARM_PMU_Enable();
        DCB->DEMCR |= DCB_DEMCR_TRCENA_Msk;
        ARM_PMU_CYCCNT_Reset();
        ARM_PMU_CNTR_Enable(PMU_CNTENSET_CCNTR_ENABLE_Msk);
        initialized = true;
    }
    return ARM_PMU_Get_CCNTR();
}

static int argmax_f32(const float *v, int n)
{
    int best = 0;
    float best_v = v[0];
    for (int i = 1; i < n; i++) {
        if (v[i] > best_v) { best_v = v[i]; best = i; }
    }
    return best;
}

/* Numerically stable softmax (single-pass for n=5 is trivial but keep general). */
static void softmax_f32(const float *logits, float *probs, int n)
{
    float max = logits[0];
    for (int i = 1; i < n; i++) if (logits[i] > max) max = logits[i];

    float sum = 0.0f;
    for (int i = 0; i < n; i++) {
        probs[i] = expf(logits[i] - max);
        sum += probs[i];
    }
    if (sum > 0.0f) {
        for (int i = 0; i < n; i++) probs[i] /= sum;
    }
}

void hal_entry(void)
{
    SEGGER_RTT_ConfigUpBuffer(0, NULL, NULL, 0, SEGGER_RTT_MODE_BLOCK_IF_FIFO_FULL);
    SEGGER_RTT_WriteString(0, "\r\n=== Melon Disease Edge Classifier (RA8P1 + Ethos-U55) ===\r\n");

    /* --- NPU init via FSP module --- */
    if (RM_ETHOSU_Open(&g_rm_ethosu0_ctrl, &g_rm_ethosu0_cfg) != FSP_SUCCESS) {
        SEGGER_RTT_WriteString(0, "[fatal] RM_ETHOSU_Open failed\r\n");
        return;
    }

    ETHOSU_PMU_Enable(&g_ethosu0);
    const int events[] = {
        ETHOSU_PMU_NPU_IDLE,
        ETHOSU_PMU_NPU_ACTIVE,
        ETHOSU_PMU_AXI0_ENABLED_CYCLES,
        ETHOSU_PMU_AXI1_ENABLED_CYCLES,
    };
    const int n_events = (int)(sizeof(events) / sizeof(events[0]));
    for (int i = 0; i < n_events; i++) {
        ETHOSU_PMU_Set_EVTYPER(&g_ethosu0, i, events[i]);
        ETHOSU_PMU_CNTR_Enable(&g_ethosu0, 1u << i);
    }
    ETHOSU_PMU_CNTR_Enable(&g_ethosu0, ETHOSU_PMU_CCNT_Msk);

    /* --- inference loop over 5 test images --- */
    int hits = 0;
    uint64_t total_cpu_cycles = 0;
    uint64_t total_npu_active = 0;

    for (int idx = 0; idx < MELON_N_TEST_IMGS; idx++) {

        /* Preprocess into RUHMI's input buffer (NCHW float, normalized). */
        float *input_ptr = GetModelInputPtr_input();
        melon_preprocess_u8_hwc_to_f32_nchw(MELON_TEST_IMGS[idx], input_ptr);

        /* Reset counters. */
        ETHOSU_PMU_CYCCNT_Reset(&g_ethosu0);
        ETHOSU_PMU_EVCNTR_ALL_Reset(&g_ethosu0);
        uint32_t cpu_start = pmu_get_cycles();

        RunModel(false);

        uint32_t cpu_cycles  = pmu_get_cycles() - cpu_start;
        /* Ethos-U PMU is half-rate vs M85 core, so multiply by 2 to compare. */
        uint32_t npu_idle    = ETHOSU_PMU_Get_EVCNTR(&g_ethosu0, 0) * 2;
        uint32_t npu_active  = ETHOSU_PMU_Get_EVCNTR(&g_ethosu0, 1) * 2;
        uint32_t npu_axi0_en = ETHOSU_PMU_Get_EVCNTR(&g_ethosu0, 2) * 2;
        uint32_t npu_axi1_en = ETHOSU_PMU_Get_EVCNTR(&g_ethosu0, 3) * 2;

        const float *logits = GetModelOutputPtr_logits_70207();
        float probs[MELON_N_CLASSES];
        softmax_f32(logits, probs, MELON_N_CLASSES);

        int pred = argmax_f32(probs, MELON_N_CLASSES);
        int conf_pct = (int)(probs[pred] * 100.0f + 0.5f);
        int label = MELON_TEST_LABELS[idx];
        const char *ok = (pred == label) ? "OK" : "MISS";
        if (pred == label) hits++;

        total_cpu_cycles += cpu_cycles;
        total_npu_active += npu_active;

        SEGGER_RTT_printf(0,
            "\r\n[img %d] %s  ground-truth=%s\r\n", idx, MELON_TEST_IMG_NAMES[idx], MELON_CLASS_NAMES[label]);
        SEGGER_RTT_printf(0,
            "  pred = %s  conf = %d%%  [%s]\r\n", MELON_CLASS_NAMES[pred], conf_pct, ok);
        SEGGER_RTT_printf(0,
            "  cycles: total=%u  npu_active=%u  npu_idle=%u  axi0=%u  axi1=%u\r\n",
            cpu_cycles, npu_active, npu_idle, npu_axi0_en, npu_axi1_en);
        SEGGER_RTT_printf(0,
            "  cpu_other = %u (= total - npu_active)\r\n",
            (uint32_t)(cpu_cycles > npu_active ? cpu_cycles - npu_active : 0));
    }

    SEGGER_RTT_printf(0,
        "\r\n=== summary  acc=%d/%d  avg_cpu=%u  avg_npu_active=%u cycles ===\r\n",
        hits, MELON_N_TEST_IMGS,
        (uint32_t)(total_cpu_cycles / MELON_N_TEST_IMGS),
        (uint32_t)(total_npu_active / MELON_N_TEST_IMGS));

    ETHOSU_PMU_Disable(&g_ethosu0);
    if (RM_ETHOSU_Close(&g_rm_ethosu0_ctrl) != FSP_SUCCESS) {
        SEGGER_RTT_WriteString(0, "[warn] RM_ETHOSU_Close failed\r\n");
    }

    /* Idle loop — keep RTT channel alive for the user to scroll back. */
    while (1) { __WFI(); }
}
