/* Auto-generated by scripts/img_to_header.py — do not edit by hand. */
#ifndef MELON_TEST_IMGS_H
#define MELON_TEST_IMGS_H

#include <stdint.h>

#define MELON_IMG_H        160
#define MELON_IMG_W        160
#define MELON_IMG_C        3
#define MELON_IMG_SIZE     (160 * 160 * 3)  /* = 76800 bytes */
#define MELON_N_TEST_IMGS  5
#define MELON_N_CLASSES    5

/* HWC uint8 (0..255). Device preprocesses to NCHW float ImageNet-normalized. */
extern const uint8_t MELON_TEST_IMGS[MELON_N_TEST_IMGS][MELON_IMG_SIZE];
extern const uint8_t MELON_TEST_LABELS[MELON_N_TEST_IMGS];
extern const char *const MELON_TEST_IMG_NAMES[MELON_N_TEST_IMGS];
extern const char *const MELON_CLASS_NAMES[MELON_N_CLASSES];

#endif /* MELON_TEST_IMGS_H */
