"""Phase 4: pick 5 test images (one per class) → C header + impl file.

Outputs (rooted at --out-dir, default firmware/src/):
    test_imgs.h   — declarations: dims, class names, label/name tables
    test_imgs.c   — implementations: const uint8_t TEST_IMGS[5][160*160*3]
                    (HWC uint8 raw, NOT pre-normalized — device does the math)

The image bytes are taken straight from data/processed/test/<class>/*.jpg with
PIL (already letterboxed 160×160 by Phase 1, so no further resize needed).

Usage:
    python scripts/img_to_header.py
    python scripts/img_to_header.py --out-dir firmware/src --seed 42
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _common import CLASSES, CLASS_TO_IDX  # noqa: E402


def pick_one_per_class(data_root: Path, seed: int) -> list[tuple[str, str, Path]]:
    """For each of the 5 classes, deterministically pick one test image.
    Returns list of (class_name, stem, image_path)."""
    rng = np.random.default_rng(seed)
    picks: list[tuple[str, str, Path]] = []
    for cls in CLASSES:
        d = data_root / "test" / cls
        candidates = sorted(d.glob("*.jpg"))
        if not candidates:
            raise SystemExit(f"[fail] no images in {d}")
        idx = int(rng.integers(0, len(candidates)))
        chosen = candidates[idx]
        picks.append((cls, chosen.stem, chosen))
    return picks


def emit_byte_array(name: str, data: bytes, out) -> None:
    """Write a C-formatted hex byte array."""
    out.write(f"    {{")
    for i, b in enumerate(data):
        if i % 16 == 0:
            out.write("\n        ")
        out.write(f"0x{b:02X}, ")
    out.write("\n    },\n")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--data-root", type=Path, default=Path("data/processed"))
    ap.add_argument("--out-dir", type=Path, default=Path("firmware/src"))
    ap.add_argument("--target-size", type=int, default=160)
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)
    picks = pick_one_per_class(args.data_root, args.seed)

    H = W = args.target_size
    C = 3
    bytes_per_img = H * W * C

    # ---------------- test_imgs.h ----------------
    header = args.out_dir / "test_imgs.h"
    with header.open("w", encoding="utf-8") as f:
        f.write("/* Auto-generated by scripts/img_to_header.py — do not edit by hand. */\n")
        f.write("#ifndef MELON_TEST_IMGS_H\n#define MELON_TEST_IMGS_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define MELON_IMG_H        {H}\n")
        f.write(f"#define MELON_IMG_W        {W}\n")
        f.write(f"#define MELON_IMG_C        {C}\n")
        f.write(f"#define MELON_IMG_SIZE     ({H} * {W} * {C})  /* = {bytes_per_img} bytes */\n")
        f.write(f"#define MELON_N_TEST_IMGS  {len(picks)}\n")
        f.write(f"#define MELON_N_CLASSES    {len(CLASSES)}\n\n")
        f.write("/* HWC uint8 (0..255). Device preprocesses to NCHW float ImageNet-normalized. */\n")
        f.write("extern const uint8_t MELON_TEST_IMGS[MELON_N_TEST_IMGS][MELON_IMG_SIZE];\n")
        f.write("extern const uint8_t MELON_TEST_LABELS[MELON_N_TEST_IMGS];\n")
        f.write("extern const char *const MELON_TEST_IMG_NAMES[MELON_N_TEST_IMGS];\n")
        f.write("extern const char *const MELON_CLASS_NAMES[MELON_N_CLASSES];\n\n")
        f.write("#endif /* MELON_TEST_IMGS_H */\n")
    print(f"[wrote] {header}")

    # ---------------- test_imgs.c ----------------
    impl = args.out_dir / "test_imgs.c"
    with impl.open("w", encoding="utf-8") as f:
        f.write("/* Auto-generated by scripts/img_to_header.py — do not edit by hand. */\n")
        f.write('#include "test_imgs.h"\n\n')
        f.write("/* Class names match training order (CLASSES tuple in _common.py). */\n")
        f.write("const char *const MELON_CLASS_NAMES[MELON_N_CLASSES] = {\n")
        for c in CLASSES:
            f.write(f'    "{c}",\n')
        f.write("};\n\n")

        f.write("const char *const MELON_TEST_IMG_NAMES[MELON_N_TEST_IMGS] = {\n")
        for cls, stem, _ in picks:
            f.write(f'    "{cls}/{stem}",\n')
        f.write("};\n\n")

        f.write("const uint8_t MELON_TEST_LABELS[MELON_N_TEST_IMGS] = {\n")
        for cls, _, _ in picks:
            f.write(f"    {CLASS_TO_IDX[cls]},  /* {cls} */\n")
        f.write("};\n\n")

        # The big payload — keep in default rodata; user can map to OSPI flash if needed.
        f.write("const uint8_t MELON_TEST_IMGS[MELON_N_TEST_IMGS][MELON_IMG_SIZE] = {\n")
        for cls, stem, path in picks:
            img = Image.open(path).convert("RGB")
            if img.size != (W, H):
                # Defensive — Phase 1 should have produced exactly 160×160 already.
                img = img.resize((W, H), Image.BILINEAR)
            arr = np.asarray(img, dtype=np.uint8)  # (H, W, C)
            f.write(f"    /* image {CLASS_TO_IDX[cls]}: {cls}/{stem} */\n")
            emit_byte_array(stem, arr.tobytes(), f)
        f.write("};\n")
    sz_mb = impl.stat().st_size / (1024 * 1024)
    print(f"[wrote] {impl}  ({sz_mb:.2f} MB)")

    print("\n[summary] picked images:")
    for cls, stem, path in picks:
        print(f"  class {CLASS_TO_IDX[cls]} {cls:<10}  {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
